### ISSUE TITLE
Static column backports

### ISSUE THREAD

**Issue by eprothro** [instaclustr/cassandra#2]
Just learned of this LTS branch from jeffj, thank y'all for making public!

We've been plagued by issues related to static columns. Specifically 3 related issues that are now all addressed in trunk:

https://issues.apache.org/jira/browse/CASSANDRA-11988
https://issues.apache.org/jira/browse/CASSANDRA-12336
https://issues.apache.org/jira/browse/CASSANDRA-12582

Any thoughts about including these 3 backports to make 3.7 LTS friendly to static column users?

We're interested in UDT support added by 7423, but these static column issues aren't fixed in vanilla 3.7, of course.

**Comment by kgreav** [comment]
Shouldn't be a problem, I've got a branch where I'm currently merging and testing a bunch of backports. I've included these 3 and they appear to merge cleanly. I'll run through the tests/dtests next week and merge the branch in (if everything works).

**Comment by eprothro** [comment]
thanks!

**Comment by kgreav** [comment]
Sorry for the delay, this has now been merged into the cassandra-3.7-instaclustr branch. Tests seem to be fine but let us know if you see any issues.
